services:
  web:
    image: recipe-api
    environment:
      MONGODB_URI: mongodb://db:27017/recipes
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - db:/data/db
  docs:
    image: swaggerapi/swagger-ui
    volumes:
      - ./recipe-api.yaml:/recipe-api.yaml
    environment:
      URL: http://localhost:8080/web/static/recipe-api.yaml
  proxy:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - docs
volumes:
  db: